name: 'Test'
on:
  push:
    branches: ['main']
  pull_request:

jobs:
  node-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: pnpm
      - name: Install npm dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build
      - name: Run Tests
        run: pnpm test
      - name: Test Example
        run: |
          cd example
          pnpm i
          pnpm example
